import React, { useEffect, useRef, useState } from 'react';
import { Html5QrcodeScanner, Html5Qrcode } from 'html5-qrcode';
import { X, Camera } from 'lucide-react';

interface QrCodeScannerProps {
  onScan: (batchId: string) => void;
  onClose: () => void;
}

const QrCodeScanner: React.FC<QrCodeScannerProps> = ({ onScan, onClose }) => {
  const scannerRef = useRef<Html5QrcodeScanner | null>(null);
  const [error, setError] = useState<string>('');

  useEffect(() => {
    const config = {
      fps: 10,
      qrbox: { width: 250, height: 250 },
      aspectRatio: 1.0,
    };

    const scanner = new Html5QrcodeScanner('qr-reader', config, false);
    scannerRef.current = scanner;

    scanner.render(
      (decodedText) => {
        // Extract batch ID from the scanned URL or text
        let batchId = '';
        
        try {
          // If it's a URL, extract batch ID from query parameters
          if (decodedText.includes('http')) {
            const url = new URL(decodedText);
            batchId = url.searchParams.get('id') || url.searchParams.get('batch') || '';
          } else {
            // If it's direct batch ID
            batchId = decodedText;
          }
          
          if (batchId) {
            scanner.clear();
            onScan(batchId);
          } else {
            setError('Invalid QR code format. Please scan a valid AgriChain QR code.');
          }
        } catch (err) {
          setError('Error processing QR code. Please try again.');
        }
      },
      (errorMessage) => {
        // Handle scan error (don't show all errors as they can be noisy)
        if (errorMessage.includes('NotAllowedError')) {
          setError('Camera permission denied. Please allow camera access and try again.');
        }
      }
    );

    return () => {
      if (scannerRef.current) {
        scannerRef.current.clear().catch(console.error);
      }
    };
  }, [onScan]);

  const handleClose = () => {
    if (scannerRef.current) {
      scannerRef.current.clear().catch(console.error);
    }
    onClose();
  };

  const handleFileUpload = async (event: React.ChangeEvent<HTMLInputElement>) => {
    try {
      const file = event.target.files?.[0];
      if (!file) return;
      // Stop live scanner if running
      if (scannerRef.current) {
        await scannerRef.current.clear().catch(() => undefined);
      }

      const html5Qr = new Html5Qrcode('qr-reader');
      try {
        const result = await html5Qr.scanFileV2(file);

        let batchId = '';
        if (result?.decodedText?.includes('http')) {
          const url = new URL(result.decodedText);
          batchId = url.searchParams.get('id') || url.searchParams.get('batch') || '';
        } else {
          batchId = result?.decodedText || '';
        }

        await html5Qr.clear();

        if (batchId) {
          onScan(batchId);
        } else {
          setError('Invalid QR code. Please upload the QR image generated by this app.');
        }
      } catch (e) {
        setError('Could not read QR from file. Please try a clearer image.');
        await html5Qr.clear().catch(() => undefined);
      }
    } catch (e) {
      setError('File scan failed.');
    }
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-75 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-md w-full">
        <div className="flex items-center justify-between p-6 border-b">
          <div className="flex items-center">
            <Camera className="h-6 w-6 text-blue-500 mr-3" />
            <h2 className="text-xl font-bold text-gray-800">Scan QR Code</h2>
          </div>
          <button
            onClick={handleClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <X className="h-6 w-6 text-gray-500" />
          </button>
        </div>
        
        <div className="p-6">
          <div id="qr-reader" className="w-full"></div>
          <div className="mt-4">
            <label className="block text-sm font-medium text-gray-700 mb-1">Or upload QR image/PDF</label>
            <input
              type="file"
              accept="image/*"
              onChange={handleFileUpload}
              className="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"
            />
            <p className="mt-2 text-xs text-gray-500">If camera is unavailable, upload the downloaded QR image. If you have a PDF, open it and take a clear screenshot of the QR, then upload the image.</p>
          </div>
          
          {error && (
            <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-sm text-red-700">{error}</p>
            </div>
          )}
          
          <div className="mt-4 text-center">
            <p className="text-sm text-gray-600">
              Position the QR code within the frame to scan automatically
            </p>
          </div>
        </div>
        
        <div className="px-6 pb-6">
          <button
            onClick={handleClose}
            className="w-full py-2 px-4 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    </div>
  );
};

export default QrCodeScanner;